### ISSUE TITLE
TeamSpeak recording server

### ISSUE THREAD

**Issue by tyranron** [ALLATRA-IT/ephyr#12]
## Motivation

There is a need in organizing recording of translations done in TeamSpeak separately from a mixing server.

## Overview

There should be a standalone service, which on command starts capturing audio from TeamSpeak channels [according to the mixing `Spec`](https://github.com/ALLATRA-IT/ephyr/blob/v0.2.0/src/spec.rs) and writes captured audion to the files until the `stop` command is received. After `stop` command is received, the result audio files shoud be uploaded to [Google Drive](https://www.google.com/drive/).

### HTTP API

Recording server should represent a dead simple REST API server with the only two endpoints:
- `POST /stream/<stream-name>` (idempotent): starts recording for a `<stream-name>` stream declared in [mixing `Spec`](https://github.com/ALLATRA-IT/ephyr/blob/v0.2.0/src/spec.rs).
- `PUT /stream/<stream-name>` (idempotent): stops recording for a `<stream-name>` stream declared in [mixing `Spec`](https://github.com/ALLATRA-IT/ephyr/blob/v0.2.0/src/spec.rs).

_Instrumentation_: [`actix-web`](https://docs.rs/actix-web) shoud be used to implement the HTTP server.

#### Authorization

Both endpoints shoud be protected with a [Bearer Token HTTP authorization](https://tools.ietf.org/html/rfc6750).

The server should read on startuo from its configuration a hash of the bearer token and authorize all HTTP requests against it.

_Instrumentation_:
- [`actix-web-httpauth`](https://docs.rs/actix-web-httpauth)  shoud be used to implement HTTP authorization.
- [`argon2`](https://docs.rs/rust-argon2) should be used for validating bearer tokens.

### CLI (command line interface)

The server should be represented as a `serve recorder` sub-command of `ephyr` binary. The supported flags should be:
- `--mixing-spec=<file-path>`: path to the file containing the [mixing `Spec`](https://github.com/ALLATRA-IT/ephyr/blob/v0.2.0/src/spec.rs) to perform recoding in accordance with.
- `-a, --auth-token-hash=<argon2-hash>`: [Argon2 hash](https://antelle.net/argon2-browser/) to validate bearer tokens in HTTP requests against.
- `-o, --out-dir=<directory-path>`: path to the directory where recorded files should be persisted in, before they're updloaded to Google Drive.
- `--gdrive-client-id=<id-string>`: `CLIENT_ID` for accessing Google Drive via API.
- `--gdrive-client-secret=<secret-string>`: `CLIENT_SECRET` for accessing Google Drive via API.
- `--ffmpeg`: path to FFmpeg binary to use.
- `--http-ip`: IP address for `recorder` server to listen HTTP requests on.
- `--http-port`: Port for `recorder` server to listen HTTP requests on.

#### Start recoding

Once `POST /stream/<stream-name>` request is received, the following should be performed:
1. Check whether `<stream-name>` is contained in [mixing `Spec`](https://github.com/ALLATRA-IT/ephyr/blob/v0.2.0/src/spec.rs).
2. Accoding to [the `Spec](https://github.com/ALLATRA-IT/ephyr/blob/v0.2.0/src/spec.rs) spawn and run all the required [`teamspeak::Input`s](https://github.com/ALLATRA-IT/ephyr/blob/v0.2.0/src/input/teamspeak.rs) [`io::copy`ing](https://docs.rs/tokio/0.2.22/tokio/io/fn.copy.html) the audio into spawned FFmped process (for each TeamSpeack channel a separate process should be spawned).
3. FFmpeg should receive `f32be` PCM audio-data from STDIN and remux it into MP3 320kbps and write it into the file (in `--out-dir`) named as `<stream-name>_<lang>_<YYYY-MM-DD>.mp3`. The file _shoud not be overwritten_ if it exists already, but rather appended with new data.

#### Finish recording

Once `PUT /stream/<stream-name>` request is received, the following should be performed:
1. Check whether `<stream-name>` is contained in [mixing `Spec`](https://github.com/ALLATRA-IT/ephyr/blob/v0.2.0/src/spec.rs) and is in a `recording` state now.
2. Finish the recoding, by stopping all the FFmpeg processes related to `<stream-name>`.
3. Upload all the writen MP3 files to Google Drive. Do not replace if there is a name collision, but rather rename suffix the name with the current time `_<HH:MM::SS>` and retry until succeed.
4. Cleanup successfully uploaded MP3 files from local files.

## Roadmap

Each step should be implemented as a separate MR. Mainline branch is: `recorder`.

- [ ] 1. Bootstrap the HTTP server with required endpoints, without any authorization.
- [ ] 2. Implement reading [mixing `Spec`](https://github.com/ALLATRA-IT/ephyr/blob/v0.2.0/src/spec.rs) and keeping it in the server's state. Keeping validating in HTTP endpoints whether the requested `<stream-name>` exists.
- [ ] 3. Implement recording starting.
- [ ] 4. Implement recording finishing, without Google Drive uploading.
- [ ] 5. Implement uploading to GoogleDrive.
- [ ] 6. Implement authorization via bearer HTTP token.
- [ ] 7. Polish and finish the CLI.

**Comment by mikowiec** [comment]
Thank

**Comment by tyranron** [comment]
Having #26 implemented, may be built on top of that.

**Comment by iAnanich** [comment]
can this be implemented as optional feature for mixin source? simply a button to start recording. 
And it would be great to save file not only on server, but stream it to user's browser

**Comment by skhalymon** [comment]
@iAnanich yes, it's definitely the option here. 

@digest0r has proposed that we could use current save to file option with muted origin. But In this case, we would have big file size. And another downside that we need to create separate mixers to save that files. We cannot utilize existing `re` servers.

The easy solution to decrease file size, we could add option to save file to MP3. We already have really similar MP3 output, so need a little modify it. But still, we won't be able to utilize the same `re` servers.


Well, need to take a call with UI\UX team here :)
