### ISSUE TITLE
WebRTC conferences forwarded to RTMP with custom layouts

### ISSUE THREAD

**Issue by tyranron** [ALLATRA-IT/ephyr#14]
## Synopsis

There is a need for a simple [WebRTC]-based platform with predefined custom scene layouts.

The common scenatio will be:
1. A _Host_ creates a _Room_, choosing the number of participants and some predefined scene layout.
2. After starting the _Room_ can be shared via a unique link, using which participants join the conference.
3. The whole video scene of the _Room_ with all the audio should be forwarded to some [RTMP](https://en.wikipedia.org/wiki/Real-Time_Messaging_Protocol) destination, for the purpose of streaming the whole conference to YouTube, Facebook, etc.
4. Each participant should be able to mute its audio (possibly, video).
5. The _Host_ should be able to mute participants and kick them off, if necessary.

## Design considerations

- Predefined scene layouts should be defined statically, and may be registered on the server staring (so provided by a config option).
- Each _Room_ should have a uniquely generated ID (used in the link). This ID __should not be easily guessable__ to avoid the situation of malicious user joining the _Room_.
- To distinguish the _Host_ from other participants, after the _Room_ creation it should be provided with some session _Secret_, saved on the client side until the _Room_ is destroyed.
- A _Room_ is destroyed either when the _Host_ explicitly does so, or when all the participants left the _Room_.
- Once _Host_ starts _Room_ it should play on [RTMP] destinations even if nobody joined the _Room_ and the _Host_ is fully muted (all screens are black).
- A _Host_ should be able to specify the desired [RTMP] destinations (up to 5, for the start).
- When _Host_ mutes someone, the mutee shouldn't be able to unmute himself.
- For better quality from clients, the scene mixing should happen on the server side, so all the clients will have only their video/audio sending to server, and receiving from the server a video/audio of already mixed scene, rather than separate streams for each participants. This way the client may have better throughput, so quality.

## Roadmap
- [x] 0. Investigate existing open source [WebRTC] media server and how they can fit into the scenario.
- [ ] 1. Implement a single-scene prototype to PoC (proof-of-concept) the chosen technology.
- [ ] 2. Implement a better, polished, extensible and full-featured solution.

[WebRTC]: https://webrtc.org
[RTMP]: https://en.wikipedia.org/wiki/Real-Time_Messaging_Protocol

**Comment by tyranron** [comment]
## [Janus]

[Janus] is a [SFU] (selective forwarding unit) written in C. So, it doesn't do any server-side mixing out-of-the-box and just relays [WebRTC] media streams "as is".

However, [Janus] capabilities are extensible with [plugins][1].
- [`VideoRoom` plugin][2]  implements [SFU] videoconferencing.
- [`Streaming` plugin][3] allows WebRTC peers to watch/listen to pre-recorded files or media generated by another tool.
- [`Record&Play` plugin][4] allows to record a message sent with WebRTC in the format defined in `recorded.c` (MJR recording) and subsequently replay this recording (or other previously recorded) through WebRTC as well.

So, [Janus plugins][1] do not offer any scene mixing capabilities, or RTMP restreaming out-of-the box too.

### Fitting the problem

Ok, so [FFmpeg] could handle the scene mixing on the server side and forwarding it to RTMP endpoints. However, it won't relax the client's througput, as clients will be connected to each other via separate WebRTC media streams anyway.

Going this way, we should find a feasible way to feed [Janus] streams into the [FFmpeg]. There are numerous discussions and solutions out there:
- [Video recording: combine all participants' videos into custom layout (single file)](https://groups.google.com/g/meetecho-janus/c/XElgkCR737g)
- https://github.com/mvnrsa/janus-combine-video
- https://github.com/atyenoria/janus-webrtc-gateway-docker

### Possible design

All they are basically do the following:
- Use [`Record` plugin][4] to dump each participant's media stream to a separate file.
- Use [`VideoRoom` plugin][2] to detect when there appeares/disapperes meda stream from some participant.
- Use [FFmpeg] to mix the written files on-the-fly, and re-run [FFmpeg] process every time participants change.

Doing this way imposes [some problems with correct mixing](https://groups.google.com/g/meetecho-janus/c/XElgkCR737g/m/sACEQlcfAwAJ):
> 2) shifts between videos of different participants.
> For example, User1 joined a video room at X timestamp, then User2 joined a video room at X+3 timestamp.
> So when combining into a single video file we should take into account this shift and start play the 2nd video not from start, but after 3 seconds.

And has consequences on the stream stability, as FFmpeg should be restarted on any change.

The good part is that it's quite OK variant in the aspect of resources usage: [Janus] is quite good at handling many [WebRTC] connections due to being [SFU], and the [FFmpeg] is quite good in mixing and RTMP publishing.

### Alternative ways

The alternative way, to perform the mixing correctly is to spin-up a headless browser and connect to the ongoing converence, mix it right there through HTML canvas and grab via [FFmpeg]. But this one is [too poor for scalability](https://github.com/atyenoria/janus-webrtc-gateway-docker#wip-mixing-for-janus-recording):
> 2. jibri's solution headless chrome + grab the screen with ffmpeg is agressive approach. It is possible, but the scalabilitiy is poor. For example, the jibri's ffmpeg + chrome process consumes about 300% in my vps server.


[FFmpeg]: https://ffmpeg.org/
[Janus]: https://janus.conf.meetecho.com/index.html
[SFU]: https://webrtcglossary.com/sfu/
[WebRTC]: https://webrtc.org

[1]: https://janus.conf.meetecho.com/docs/pluginslist.html
[2]: https://janus.conf.meetecho.com/docs/videoroom.html
[3]: https://janus.conf.meetecho.com/docs/streaming.html
[4]: https://janus.conf.meetecho.com/docs/recordplay.html

**Comment by tyranron** [comment]
## [Kurento] feat. [OpenVidu]

[Kurento] is a [MCU] (multipoint conferencing unit) written in C++. It's capable of mixing WebRTC media streams and has [quite rich capabilities](https://doc-kurento.readthedocs.io/en/6.14.0/features/kurento_api.html#media-elements-and-media-pipelines) of building media processing pipelines, even allows using [arbitrary Gstreamer elements](https://doc-kurento.readthedocs.io/en/6.14.0/features/kurento_api.html#filters).

[OpenVidu] is a server-side [wrapper](https://docs.openvidu.io/en/2.15.0/#how-does-openvidu-work) of [Kurento] written in Java, aiming to simplify using [Kurento] for common cases, and providing out-of-the-box solution for video conferences, video calls, etc.

### Fitting the problem

[Kurento] allows to prepare the desired media pipeline by composing it from the desired [`WebRtcEndpoints`](https://doc-kurento.readthedocs.io/en/6.14.0/features/kurento_api.html#endpoints), sinking them into the [`CompositeHub`](https://doc-kurento.readthedocs.io/en/6.14.0/features/kurento_api.html#hubs), so mixing in the single grid, and then writing to the file via [`RecorderEndpoint`](https://doc-kurento.readthedocs.io/en/6.14.0/features/kurento_api.html#endpoints). The flexibility here is that we can go far beyond that by composing almost any desired media pipeline.

[OpenVidu] already implements the notion of _Room_ and _Session_. So videoconferences with the desired count of participants works almost out-of-the-box. It also allows to [record the mixed video conference](https://docs.openvidu.io/en/2.15.0/advanced-features/recording/#composed-recording), and even [supports custom layouts](https://docs.openvidu.io/en/2.15.0/advanced-features/recording/#custom-recording-layouts). Even [screen sharing](https://docs.openvidu.io/en/2.15.0/advanced-features/screen-share/) is supported.

As for restreaming to RTMP destination, everything is not so shiny. There is not standard way at the moment, and one should use [FFmpeg] for that. Capturing mixed stream to [FFmpeg] can be done either from the recorded file, or directly from [`RtpEndpoint` exposed by Kurento](https://openvidu.discourse.group/t/webrtc-to-rtmp-stream-at-kms/656/2), which however required forking [OpenVidu] at the moment. Another option to investigate is to use [`rtmpsink` Gstreamer element](https://gstreamer.freedesktop.org/documentation/rtmp/rtmpsink.html?gi-language=c).


### Possible design

- Server side solution uses [OpenVidu] to configure conference.
- Client side solution reuses [OpenVidu] client library and even some demo example.
- Server side solution spawns [FFmpeg] processes for restreaming RTMP from `RtpEndpoint` (or file) and reports about problems to client side.



[Kurento]: https://www.kurento.org/
[OpenVidu]: https://openvidu.io/index
[MCU]: https://webrtcglossary.com/mcu/
[FFmpeg]: https://ffmpeg.org/

**Comment by tyranron** [comment]
## [Jitsi]

[Jitsi] is a [SFU] (selective forwarding unit) written [in Java][1]. As a platform, [Jitsi] consists of [several components](https://github.com/jitsi):
- [`jitsi-videobridge`] is the [SFU] heart;
- [`jitsi-meet`] is an on-top ready-to-go wrapper application for video conferences;
- [`jibri`] is an application for recording and streaming [`jitsi-meet`] conferences.


## Fitting the problem

[`jitsi-meet`] implements most of the desired features and [`jibri`] provides out-of-the box solution for restreaming to RTMP desitnations. However, too simple it lacks some features, so in-the-wild restreaming is usually done with [FFmpeg] and/or additional RTMP server:
- https://community.jitsi.org/t/stream-to-any-or-multiple-rtmp-destinations-record-simultaneously/51943/20

However, such proposed solutions lack the possibility to set RTMP destinations dynamically (when the server is already running).

As for composing the scene layout,  [`jitsi-meet`] is not quite flexible in providing options, so should be forked.


## Possible design

As [`jibri`] is quite a heavy capturing (running browser for that), it seems reasanoble to decouple the deployment into two separate servers: one hosts just [`jitsi-videobridge`], another one [`jibri`] and the controlling unit.



[Jitsi]: https://jitsi.org/
[FFmpeg]: https://ffmpeg.org/
[SFU]: https://webrtcglossary.com/sfu/
[WebRTC]: https://webrtc.org

[`jitsi-meet`]: https://github.com/jitsi/jitsi-meet
[`jitsi-videobridge`]: https://github.com/jitsi/jitsi-videobridge
[`jibri`]: https://github.com/jitsi/jibri

[1]: https://github.com/jitsi/jitsi-videobridge

**Comment by tyranron** [comment]
## [SRS]

[SRS] is industrial-strength live streaming cluster. However it has only [initial support of WebRTC](https://github.com/ossrs/srs/issues/307), which is able to play WebRTC only. So, is insuitable for building video conferences, at the moment.




[SRS]: https://github.com/ossrs/srs

**Comment by tyranron** [comment]
Moved to AllatRa Meet project.
