### ISSUE TITLE
Emerge mixer into re-streamer

### ISSUE THREAD

**Issue by tyranron** [ALLATRA-IT/ephyr#23]
`mixer` and `restreamer` components are quite similar in what they're doing and how are they used. So, `mixer` capabilities can be emerged into `restreamer` itself.

## Roadmap

- [x] 1. Support mixing with TeamSpeak links in re-streamer Outputs
- [x] 2. Support on-fly audio volume tuning
- [ ] 3. Support on-fly delay tuning for TeamSpeak links
