### ISSUE TITLE
Set of UI enhancements

### ISSUE THREAD

**Issue by skhalymon** [ALLATRA-IT/ephyr#35]
- [x] **Allow to change document.title**. When a lot of instances being used would be cool to be able to change the title of each site. #43
- [x] **Display amount of all inputs and amount of all outputs for server** #49
- [x] **Add link to broadcast in social network**. It should open in new window when click on it. #60 
- [x] **Do not close modals by clicking outside of it**. #49
- [x] **Save and close modal by pressing Enter** #78
- [x] **Add buttons Run ALL, Stop All for all outputs of all inputs**. (Should show confirmation dialog) #49

**Comment by PavelKushnirchuk** [comment]
Moved one list item to separate issue becuase it can be good starting point for newcomer to get aquinted with UI part of the project
